version: '3.1'

services:

  db:
    image: postgres:16.0-bullseye
    restart: always
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: postcont
    ports:
      - 5434:5432